### PR TITLE
Trend micro edr updates

### PR DESCRIPTION
**Pull request by MyPeaches**
## Description

Please provide the below information so we can validate before merging:

1. Does the proposed EDR feature align with our definition of telemetry?([definition here](https://github.com/tsale/EDR-Telemetry/wiki/FAQ#5-how-is-telemetry-defined-in-this-context))
2. Could you please provide documentation to support the telemetry you are proposing?*(If it is held privately, please reach out to me or @inodee)*
3. If no documentation is available for all the categories you are proposing, could you provide screenshots or sanitized logs?

1: Yes
2: **Telemetry collected by endpoint agent from Windows** https://docs.trendmicro.com/en-us/documentation/article/trend-vision-one-what-telemetry-collect-windows

**eventId and eventSubId mapping** - https://docs.trendmicro.com/en-us/documentation/article/trend-vision-one-eventid-eventsubid-mapping#GUID-AF4EC72E-502F-4020-9C01-C7C26D5DA73E
3: Yes

## Type of change

Please delete options that are not relevant.

- [x] New feature (adding additional EDR product or proposing new event categories/sub-categories)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

This was done in combination of the publicly available documentation review and testing of specific categories outlined in the "Test in detail" section at the bottom. 
I figured any vendor contributing to this can provide a "What we capture" knowledge base article without evidence, so I've provided a few tests to validate the public KB with screenshots. More to come in the future.

- [x] Test A Physical Windows Machine with Apex One + XES in Log only
- [x] Test B Virtual EC2 Windows 11 with XES only Hypersensitivity enabled
- [x] Documentation review
(Apex One = Endpoint EPP | XES = EDR Sensor)

**Test Configuration**:
* EDR version: XES Agent 28/06/24
* Operating System version: Windows 11

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added partial tests that prove my corrections or additions are accurate
- [x] I have checked my code and corrected any misspellings

## Test in detail
**File Manipulation**

- File Deletion
File Deletion
File Deletion2
File Deletion3

-File Renaming
File Renaming

**User Account Activity**

- Local Account Creation
Local Account Creation1
Local Account Creation2
Local Account Creation3

- Local Account Modification
Local Account Modification1
Local Account Modification2
Local Account Modification3

- Local Account Deletion
Local Account Deletion1

**Network Activity**

- URL
Network Activity1
Network Activity2
Network Activity3

**Scheduled Task Activity**

- Scheduled Task Modification
Scheduled Task Modification1
Scheduled Task Modification2
Scheduled Task Modification3
Scheduled Task Modification4

- Scheduled Task Deletion
Scheduled Task Deletion1

**Service Activity**

- Service Creation
Service Creation1

- Service Modification
Service Modification1

**Driver/Module Activity**
- Driver Loaded
Driver Loaded1

**Named Pipe Activity**
- Pipe Creation
Pipe Creation1

- Pipe Connection
Pipe Connection1

**BIT JOBS Activity**

- BIT JOBS Activity
BITS JOBS Activity1
BITS JOBS Activity2
BITS JOBS Activity3

**PowerShell Activity**

- Script-Block Activity
PowerShell Activity1
PowerShell Activity2

More changes to come in time after additional testing =)

### CODE REVIEW

**Comment by MyPeaches** [comment]
Hey @tsale I've completed some further testing, let me know if I should open a new pull request for these. In the meantime, please let me know if you need anything else here. Thank you!

**Comment by tsale** [comment]
Thank you @MyPeaches for the updates! Most of the changes look good, but there are a few categories we cannot incorporate from this PR:

- Local Account Modification
- URL
- Scheduled Task Modification
- BIT JOBS Activity

These categories require telemetry events to be logged as distinct, standalone events. We can't infer activity from other events, like process execution, or rely on backend logic to detect them.

Additionally, you've marked some telemetry categories as "Via EnablingTelemetry" that should be listed as "Via EventLogs." I will address those and commit the changes in due time.

**Comment by tsale** [comment]
> Hey @tsale I've completed some further testing, let me know if I should open a new pull request for these.

@MyPeaches, please commit here and provide proof. I will wait until you commit those new updates before I go ahead with the final review. Thank you!

**Comment by MyPeaches** [comment]
Thank you @tsale ! 

I'll circle back here in a little bit. Regarding the x4 categories, I think I understand you, it didn't appear to require any backend logic to detect them (from what I could see) but I will run the telemetry-generator.ps1 and see whats generated under the raw events on these categories from the sensor itself =). 

As for the category markings, my bad! It might be best to reference what Trend stated on their telemetry page (?) for details - https://docs.trendmicro.com/en-us/documentation/article/trend-vision-one-what-telemetry-collect-windows

Cheers

**Comment by tsale** [comment]
I am working on merging this PR. I can see that a lot of the changes that you made from _Via EventLogs_ to _Yes_ are not correct. According to the official documentation, and further testing, these events are collected _**Via EventLogs**_:

CleanShot 2024-12-13 at 10 35 53@2x

As mentioned above, I have also corrected some of your events, such as _ViaEnablingTelemetry_ to _Via EventLogs_. Additionally, I have changed the URL event as we cannot see direct proof (see my comment above regarding those events).

**Review by tsale — APPROVED** [review]

**Pull request merged**
