### PR TITLE
Addition of Uptycs EDR

### PR DESCRIPTION
**Pull request by joshlemon-uptycs**
# Pull Request Template

## Description

Please provide the below information so we can validate before merging:

1. Does the proposed EDR feature align with our definition of telemetry?([definition here](https://github.com/tsale/EDR-Telemetry/wiki/FAQ#5-how-is-telemetry-defined-in-this-context))
2. Could you please provide documentation to support the telemetry you are proposing?*(If it is held privately, please reach out to me or @inodee)*
3. If no documentation is available for all the categories you are proposing, could you provide screenshots or sanitized logs?

1: YES
2: YES - will need to be provided privately or in examples.
3: YES - if needed.

## Type of change

Please delete options that are not relevant.

- [ ] Feature Improvement (non-breaking change which fixes an issue)
- [x] New feature (adding additional EDR product or proposing new event categories/sub-categories)
- [ ] This change requires a documentation update
- [ ] New tool (suggesting additional tools for improving collection and analysis)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* EDR version: 
* Operating System version: 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my corrections or additions are accurate
- [X] I have checked my code and corrected any misspellings

*Don't stress yourself out, just answer the above to the best of your ability and we can discuss in the comments 🙂*

### CODE REVIEW

**Comment by tsale** [comment]
Thank you for the PR, @joshlemon-uptycs! As discussed via DMs, please provide the evidence for me to review whenever you can.

**Comment by joshlemon-uptycs** [comment]
Done @tsale ....finally. Thanks.

**Comment by tsale** [comment]
Some info is missing, I contacted @joshlemon-uptycs via a private channel. This will be put on hold while the information is received.

**Comment by joshlemon-uptycs** [comment]
@tsale just confirming we resubmitted further information on 29th Aug....also so I don't forget I've actioned this ;)

**Comment by tsale** [comment]
Yeap, it's on the to-do. Thanks for the info @joshlemon-uptycs !

**Comment by tsale** [comment]
Thank you very much for taking the time to provide the evidence, @joshlemon-uptycs. I thoroughly reviewed your proposal and made some changes to the initial PR. Please see the attached CSV highlighting my changes along with comments for your consideration. I will give you some time to respond with any further comments before I merge this. Thank you! 🙏

[Uptycs_review.csv](https://github.com/user-attachments/files/17070333/Uptycs_review.csv)

**Comment by joshlemon-uptycs** [comment]
Thanks. We're taking a look this week then we'll get it back to you.

**Comment by joshlemon-uptycs** [comment]
Some further updates were provided privately to @tsale for review.

**Review by tsale — APPROVED** [review]
As discussed privately, this looks good for now. The only exception is the process access due to a lack of evidence. We can always add that later once you provide further information. 

Thank you so much for sharing all the details, @joshlemon-uptycs. This is a fantastic contribution, and we truly appreciate the time you took to provide the evidence and collaborate with me on this PR! 🙏

**Pull request merged**
