### PR TITLE
Expand WMI Activity category to cover all WMI Activity

### PR DESCRIPTION
**Pull request by jdu2600**
# Pull Request Template

## Description

The current "WMI Activity" category has three sub-categories to cover a single MITRE Persistence sub-technique [T1546.003 - Windows Management Instrumentation Event Subscription](https://attack.mitre.org/techniques/T1546/003/), but no sub-category to cover the MITRE Execution technique [T1047 - Windows Management Instrumentation](https://attack.mitre.org/techniques/T1047/).

Suggest that we just generalise it to all "WMI Activity" as a single category - this is consistent with the approaches for PowerShell, BITS etc.

All vendors with coverage of T1546.003 are marked as Partially for "WMI Activity" until any additional coverage of WMI Activity can be confirmed.

## Type of change

- [x] Feature Improvement (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by tsale** [comment]
Thank you for the suggestion @jdu2600, but I’d prefer to keep the sub-categories separate as they each serve a specific purpose in how we approach WMI monitoring in this project.

- **WmiEventConsumerToFilter**: This helps us track the linkage between filters and consumers, which is crucial in understanding how different WMI events are connected and triggered.
- **WmiEventConsumer**: Monitoring this category allows us to identify what specific actions are being taken when an event is triggered, giving us visibility into potential persistence mechanisms.
- **WmiEventFilter**: Filters show us the conditions under which the WMI events are triggered, which is key for detecting malicious activity that relies on WMI for automation or lateral movement.

Each of these categories provides distinct telemetry data that we need to track separately to ensure comprehensive monitoring. Let me know if you have any thoughts or further questions on this!

**Comment by jdu2600** [comment]
Absolutely agree that all of those events have value - but the level of specificity doesn't seem consistent with other sub-categories?
For example, there are [31 types of registry events](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ne-wdm-_reg_notify_class) - but we're only capturing whether telemetry is logged for three of them. 

Also, all three of those WMI events are specific to the 'Permanent WMI Event Subscription' T1546.003 sub-technique only.  Which is why every vendor supports all three - or none.
🤔 If we want to keep some specificity, we could probably get away with a single sub-category with a Partial value if all three aren't supported? Thoughts?

And what are your thoughts on telemetry for WMI method activity, WMI enumeration activity, WMI provider activity etc?
How many sub-categories do we want to add for T1047?
https://learn.microsoft.com/en-us/windows/win32/api/wbemcli/nn-wbemcli-iwbemservices
 * WMI Namespace Open
 * WMI Class Enumeration
 * WMI Class Creation/Update
 * WMI Class Deletion
 * WMI Instance Enumeration
 * WMI Instance Creation/Update
 * WMI Instance Deletion
 * WMI Object Retrieval
 * WMI Method Execution
 * WMI Query Execution

**Comment by tsale** [comment]
I appreciate your input @jdu2600! Just wanted to clarify why I prefer to keep the sub-categories (WmiEventConsumerToFilter, WmiEventConsumer, WmiEventFilter) separate. Each one highlights a unique aspect of WMI activity, providing more depth in the telemetry. 

Regarding the level of specificity, I believe these sub-categories actually provide the right level of detail. They focus on high-value WMI event types that are most relevant for threat hunting and detection. While it may seem inconsistent compared to other categories, this level of granularity is necessary to distinguish between how different parts of WMI are abused. If we were to generalize more, we might lose that critical context.

As for tracking all individual event types, that would introduce too much complexity and make it difficult to maintain consistency across the project. We’d end up with a huge variety of events, making it challenging to provide focused, actionable insights.

**Review by tsale — COMMENTED** [review]
I appreciate your input @jdu2600! Just wanted to clarify why I prefer to keep the sub-categories (WmiEventConsumerToFilter, WmiEventConsumer, WmiEventFilter) separate. Each one highlights a unique aspect of WMI activity, providing more depth in the telemetry.

Regarding the level of specificity, I believe these sub-categories actually provide the right level of detail. They focus on high-value WMI event types that are most relevant for threat hunting and detection. While it may seem inconsistent compared to other categories, this level of granularity is necessary to distinguish between how different parts of WMI are abused. If we were to generalize more, we might lose that critical context.

As for tracking all individual event types, that would introduce too much complexity and make it difficult to maintain consistency across the project. We’d end up with a huge variety of events, making it challenging to provide focused, actionable insights.

**Comment by jdu2600** [comment]
I don't quite follow your logic. 

You value specificity in telemetry and want to retain three sub-categories specifically for WMI Event Subscriptions - a single MITRE T1546.003 sub-technique.

I've observed that abuse of WMI Event Subscriptions by (non-red team) actors is mostly historic as the technique's value was heavily tied to it being unknown, and noting that this abuse can already be detected with existing process telemetry.  (That is, the value of this telemetry is now for DFIR - not EDR).

You also don't value specificity in telemetry and are concerned with introducing too many sub-categories and don't want to include any coverage for the entire the MITRE T1047 technique - which remains a highly prevalent technique by many malware families.

For hunting, there are numerous WMI queries, methods and classes that are routinely abused by malware and not covered in your telemetry .

https://attack.mitre.org/techniques/T1047/ - Windows Management Instrumentation
 * AntiVirusProduct / Win32_DeviceGuard enumeration
   * This information is only available in the WMI repository.
 * Win32_Process abuse 
   * WMI remains as one of most effective mechanisms for parent process spoofing
 * Win32_Shadowcopy abuse 
 * Win32_Environment abuse
 * Win32_ComputerSystem, Win32_SystemDriver etc host enumeration

I would have thought that there would be value in at least one sub-category for (non-Event Subscription) WMI Activity?  I agree that 10 sub-categories is far too many, but 0 is surely too few?

**Comment by tsale** [comment]
I understand your concern about specificity. While I believe the current sub-categories (WmiEventConsumer, WmiEventFilter, and WmiEventConsumerToFilter) capture the most critical aspects of WMI abuse for persistence, as a compromise, I’d be open to introducing one more sub-category focused on WMI class interaction visibility.

To clarify, this project isn’t about covering every attack technique but more about evaluating the capabilities of different EDRs in collecting relevant telemetry.

Happy to discuss further!

**Comment by jdu2600** [comment]
👍 If you re-open the PR I'll refactor it to just add a "Other WMI Activity" sub-category.

**Comment by tsale** [comment]
Sounds good. Maybe make it a bit more specific. For example, you can use the name: "WMI Method Execution".

**Comment by jdu2600** [comment]
How about "WMI Operation"?
"Method" has a very specific meaning in WMI - and only covers a subset of the security-relevant WMI events.


I also did a quick survey of WMI telemetry in a few EDRs -

https://falconforce.nl/microsoft-defender-for-endpoint-internals-0x04-timeline-telemetry/
MDE has three WMI event types that you can see in the Timeline view - WmiQuery, WmiExecMethod, CreateProcessThroughWMIAPI
This would be Partial coverage, but since this telemetry is not streamed and available for Hunting I don't think it meet this project's definition of telemetry?

Crowdstrike appears to have three WMI event types - WmiProviderRegistrationEtw, SensitiveWmiQuery, WmiCreateProcess - so looks like Partial coverage given the set of types and the filtering.

**Comment by tsale** [comment]
I'm fine with that name, yea. 

RE coverage - That’s exactly what I was concerned about. If we go ahead with this new sub-category, we’ll need to clearly define what constitutes full coverage for it. Could you help define what that would look like?

**Comment by jdu2600** [comment]
The useful set of coverage is probably queries, methods and providers.

So this powershell would give us a quick assessment of coverage -
```
PS>Get-WmiObject -Class Win32_Bios

PS> Invoke-WmiMethod -Path Win32_NetworkAdapterConfiguration -Name RenewDHCPLeaseAll

PS> $Class = New-Object Management.ManagementClass(New-Object Management.ManagementPath("Win32_Registry"))
PS> $NewClass = $Class.Derive("Not_Registry")
PS> $NewClass.Put()
```

It should generate three events. Roughly -
```
ExecQuery - root\\cimv2 : select * from Win32_Bios

ExecMethod - root\\cimv2 : Win32_NetworkAdapterConfiguration::RenewDHCPLeaseAll

PutClass - root\\cimv2 : Not_Registry
```

**Comment by jdu2600** [comment]
@tsale I've pushed the requested changes to the branch, but the PR doesn't reflect them as it is closed.
Can you re-open?  Or would you prefer a new PR?

**Comment by tsale** [comment]
We cannot introduce a new category without testing the current EDRs we have on the table.

**Comment by jdu2600** [comment]
> We cannot introduce a new category without testing the current EDRs we have on the table.

Absolutely.
I was just asking if you -
1. want me to open a **new PR** that incorporates your feedback above, or 
2.  are going to re-open **this PR** so that I can push the requested changes?

And then once you are happy with the new subcategory approach we can seek help to fill the coverage details.

**Pull request closed without merging**
